version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: medimate-mongo-prod
    environment:
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
    ports: []
    volumes:
      - mongo-data:/data/db
  backend:
    image: medimate-backend:${APP_VERSION}-${ENVIRONMENT}
    build:
      context: ./MediMate-Back-End-Web-App
      dockerfile: Dockerfile.prod
    container_name: medimate-backend-prod
    env_file:
      - ./MediMate-Back-End-Web-App/.env.prod
    environment:
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
    depends_on:
      - mongo
  frontend:
    image: medimate-frontend:${APP_VERSION}-${ENVIRONMENT}
    build:
      context: ./MediMate-Front-End-Web-App
      dockerfile: Dockerfile.prod
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: medimate-frontend-prod
    ports:
      - "80:80"
    env_file:
      - ./MediMate-Front-End-Web-App/.env.prod
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  mongo-data: