version: '3.8'
services:
# MongoDB service for testing
  mongo:
    image: mongo:7
    container_name: medimate-mongo-test
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend service for testing
  backend-test:
    build:
      context: ./MediMate-Back-End-Web-App
      dockerfile: Dockerfile.test
    container_name: medimate-backend-test
    env_file:
      - ./MediMate-Back-End-Web-App/.env.test
    command: ["npm", "run", "test"]
    depends_on:
      - mongo
    restart: "no"
    
  # Frontend service for testing
  frontend-test:
    build:
      context: ./MediMate-Front-End-Web-App
      dockerfile: Dockerfile.test
    container_name: medimate-frontend-test
    env_file:
      - ./MediMate-Front-End-Web-App/.env.test
    command: ["npm", "run", "test"]
    depends_on:
      - backend-test
    restart: "no"
volumes:
  mongo-data: